# Generated by Django 4.2.7 on 2023-11-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0010_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-dt_created']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-dt_created']},
        ),
    ]
