# Generated by Django 4.2.7 on 2023-11-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0004_review_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='dt_modified',
            new_name='dt_updated',
        ),
    ]
